#https://projecteuler.net/problem=2
#sum of all even fibonacci numbers less than 4M

#every third F is even and can be generated by:
#f(n)=4*f(n-1)+f(n-2) where f(0)=2 and f(1)=8

fnp=2 #previous even fib
fn=8 #current even fib
t=fnp #init total to the previous
while fn<4000000:
  t+=fn
  tmp=fn
  fn=4*fn+fnp
  fnp=tmp

print("highest fib number:",fn)
print("sum of even fibs less than 4M:",t)