#!/usr/bin/env bash
# =============================================================================
# trim_id3_tags.sh
# Trims leading/trailing whitespace from ID3v1 and ID3v2 tags of all MP3 files
# in a given directory (recursively).
#
# Usage:
#   chmod +x trim_id3_tags.sh
#   ./trim_id3_tags.sh /path/to/music
#   ./trim_id3_tags.sh /path/to/music --dry-run   # Preview changes only
# =============================================================================
# generated by claude code 2026-03-21

set -euo pipefail

# ── Argument parsing ──────────────────────────────────────────────────────────
if [[ $# -lt 1 ]]; then
    echo "Usage: $(basename "$0") <directory> [--dry-run]"
    exit 1
fi

TARGET_DIR="$1"
DRY_RUN=false

if [[ "${2:-}" == "--dry-run" ]]; then
    DRY_RUN=true
    echo "DRY RUN — no files will be modified"
fi

if [[ ! -d "$TARGET_DIR" ]]; then
    echo "Error: '$TARGET_DIR' is not a directory." >&2
    exit 1
fi

# ── Require Python 3 ──────────────────────────────────────────────────────────
if ! command -v python3 &>/dev/null; then
    echo "Error: python3 is required but not found." >&2
    exit 1
fi

echo "Scanning: $TARGET_DIR"
echo

# ── Inline Python script ──────────────────────────────────────────────────────
python3 - "$TARGET_DIR" "$DRY_RUN" <<'PYTHON'
import sys
import os
import struct
import re

target_dir = sys.argv[1]
dry_run    = sys.argv[2].lower() == "true"

# ── Colours ───────────────────────────────────────────────────────────────────
GREEN  = "\033[32m"
YELLOW = "\033[33m"
CYAN   = "\033[36m"
RESET  = "\033[0m"
BOLD   = "\033[1m"

changed_files = 0
total_changes = 0

# =============================================================================
# ID3v1 helpers (fixed 128-byte trailer)
# Fields: title(30), artist(30), album(30), year(4), comment(30), genre(1)
# =============================================================================
ID3V1_SIZE   = 128
ID3V1_MARKER = b"TAG"

ID3V1_FIELDS = [
    ("title",   3,  30),
    ("artist", 33,  30),
    ("album",  63,  30),
    ("year",   93,   4),
    ("comment",97,  30),
]

def read_id3v1(data):
    """Return dict of {field: bytes_value} or None if no ID3v1 tag."""
    if len(data) < ID3V1_SIZE or data[-ID3V1_SIZE:-ID3V1_SIZE+3] != ID3V1_MARKER:
        return None
    tag = data[-ID3V1_SIZE:]
    fields = {}
    for name, offset, length in ID3V1_FIELDS:
        fields[name] = tag[offset:offset+length]
    return fields

def trim_id3v1(data):
    """Return (new_data, list_of_changes) after trimming ID3v1 fields."""
    fields = read_id3v1(data)
    if fields is None:
        return data, []

    tag = bytearray(data[-ID3V1_SIZE:])
    changes = []

    # Detect ID3v1.1: comment field byte 28 == 0x00 and byte 29 != 0x00.
    # In that case byte 29 is the track number and must not be touched,
    # because track numbers 10-13 map to \x0A-\x0D which Python's strip()
    # treats as whitespace (newline, VT, FF, CR) and would silently erase.
    comment_offset = 97  # absolute offset of comment field within the 128-byte tag
    is_v1_1 = (tag[comment_offset + 28] == 0x00 and tag[comment_offset + 29] != 0x00)

    for name, offset, length in ID3V1_FIELDS:
        raw = tag[offset:offset+length]

        if name == "comment" and is_v1_1:
            # Only trim the text portion (bytes 0-27); preserve bytes 28-29
            text_raw    = raw[:28]
            track_bytes = raw[28:]          # b"\x00" + track_byte
            decoded = text_raw.rstrip(b"\x00").decode("latin-1")
            trimmed = decoded.strip()
            if trimmed != decoded:
                changes.append((f"ID3v1:{name}", repr(decoded), repr(trimmed)))
                encoded = trimmed.encode("latin-1")[:28]
                padded  = encoded.ljust(28, b"\x00") + track_bytes
                tag[offset:offset+length] = padded
        else:
            # Decode as latin-1, strip null bytes then strip whitespace
            decoded = raw.rstrip(b"\x00").decode("latin-1")
            trimmed = decoded.strip()
            if trimmed != decoded:
                changes.append((f"ID3v1:{name}", repr(decoded), repr(trimmed)))
                encoded = trimmed.encode("latin-1")[:length]
                # Pad with null bytes
                padded = encoded.ljust(length, b"\x00")
                tag[offset:offset+length] = padded

    new_data = data[:-ID3V1_SIZE] + bytes(tag)
    return new_data, changes

# =============================================================================
# ID3v2 helpers (variable-length header at file start)
# Supports v2.2, v2.3, v2.4
# =============================================================================

def syncsafe_int(b):
    """Decode a 4-byte syncsafe integer."""
    return (b[0] << 21) | (b[1] << 14) | (b[2] << 7) | b[3]

def encode_syncsafe(n):
    """Encode integer as 4-byte syncsafe."""
    return bytes([
        (n >> 21) & 0x7F,
        (n >> 14) & 0x7F,
        (n >>  7) & 0x7F,
         n        & 0x7F,
    ])

# Text frame IDs we care about (v2.3/v2.4 and their v2.2 equivalents)
TEXT_FRAME_IDS = {
    # v2.3 / v2.4
    b"TIT2", b"TPE1", b"TALB", b"TYER", b"TRCK", b"TCON",
    b"TPE2", b"TPE3", b"TPE4", b"TPOS", b"TCOM", b"TEXT",
    b"TENC", b"TCOP", b"TPUB", b"TRDA", b"TORY", b"TDRC",
    b"TDRL", b"TDTG", b"TSRC", b"TLAN", b"TKEY", b"TBPM",
    b"TSIZ", b"TFLT", b"TMED", b"TOAL", b"TOPE", b"TOWN",
    b"TRSN", b"TRSO", b"TSST", b"TIT1", b"TIT3", b"TSOP",
    b"TSOA", b"TSOT",
    # v2.2 (3-char)
    b"TT1", b"TT2", b"TT3", b"TP1", b"TP2", b"TP3", b"TP4",
    b"TAL", b"TYE", b"TRK", b"TCO", b"TEN", b"TCR", b"TPB",
    b"TDA", b"TIM", b"TRC", b"TKE", b"TLA", b"TBP", b"TLE",
    b"TSI", b"TFT", b"TMT", b"TOT", b"TOA", b"TOL", b"TOF",
    b"TOR", b"COM",
}

ENCODINGS = {
    0: "latin-1",
    1: "utf-16",
    2: "utf-16-be",
    3: "utf-8",
}

def trim_text_frame_payload(payload):
    """
    Given the raw bytes of a text frame body (encoding byte + text bytes),
    return (new_payload, original_str, trimmed_str) or None if unchanged.
    """
    if not payload:
        return None

    enc_byte = payload[0]
    encoding = ENCODINGS.get(enc_byte, "latin-1")
    text_bytes = payload[1:]

    try:
        # Strip BOM if present (utf-16)
        text = text_bytes.decode(encoding, errors="replace")
    except Exception:
        return None

    # ID3v2.4 allows multiple values separated by \x00; trim each
    if enc_byte in (1, 2):   # utf-16 variants use \x00\x00 separator
        sep = "\x00"
    else:
        sep = "\x00"

    parts = text.split(sep)
    trimmed_parts = [p.strip() for p in parts]

    if trimmed_parts == parts:
        return None   # no change

    trimmed_text = sep.join(trimmed_parts)
    try:
        new_text_bytes = trimmed_text.encode(encoding)
    except Exception:
        return None

    new_payload = bytes([enc_byte]) + new_text_bytes
    return new_payload, text.replace("\x00", "|"), trimmed_text.replace("\x00", "|")

def process_id3v2(data):
    """
    Parse ID3v2 tag, trim text frame values, return (new_data, changes).
    Supports ID3v2.2, v2.3, v2.4.
    """
    if len(data) < 10 or data[:3] != b"ID3":
        return data, []

    major   = data[3]
    # minor = data[4]
    flags   = data[5]
    tag_size = syncsafe_int(data[6:10])
    header_end = 10

    if major not in (2, 3, 4):
        return data, []

    has_extended = bool(flags & 0x40)
    frame_id_len = 3 if major == 2 else 4
    frame_size_len = 3 if major == 2 else 4

    tag_body = bytearray(data[header_end: header_end + tag_size])
    pos = 0

    # Skip extended header (v2.3/v2.4)
    if has_extended and major in (3, 4):
        if major == 3:
            ext_size = struct.unpack(">I", tag_body[pos:pos+4])[0]
            pos += 4 + ext_size
        else:
            ext_size = syncsafe_int(tag_body[pos:pos+4])
            pos += ext_size

    changes = []

    while pos + frame_id_len + frame_size_len <= len(tag_body):
        frame_id = bytes(tag_body[pos: pos + frame_id_len])

        # Padding / end of frames
        if frame_id == b"\x00" * frame_id_len or frame_id[0] == 0:
            break

        if major == 2:
            frame_size = struct.unpack(">I", b"\x00" + tag_body[pos+3:pos+6])[0]
            frame_header_size = 6
            frame_flags = b""
        elif major == 3:
            frame_size = struct.unpack(">I", tag_body[pos+4:pos+8])[0]
            frame_header_size = 10
            frame_flags = tag_body[pos+8:pos+10]
        else:  # v2.4
            frame_size = syncsafe_int(tag_body[pos+4:pos+8])
            frame_header_size = 10
            frame_flags = tag_body[pos+8:pos+10]

        payload_start = pos + frame_header_size
        payload_end   = payload_start + frame_size

        if payload_end > len(tag_body):
            break

        # Only process text frames
        if frame_id in TEXT_FRAME_IDS:
            payload = bytes(tag_body[payload_start:payload_end])
            result = trim_text_frame_payload(payload)
            if result:
                new_payload, orig, trimmed = result
                tag_body[payload_start:payload_end] = new_payload
                # Update frame size if length changed
                size_diff = len(new_payload) - len(payload)
                if size_diff != 0:
                    new_frame_size = frame_size + size_diff
                    if major == 2:
                        tag_body[pos+3:pos+6] = struct.pack(">I", new_frame_size)[1:]
                    elif major == 3:
                        tag_body[pos+4:pos+8] = struct.pack(">I", new_frame_size)
                    else:
                        tag_body[pos+4:pos+8] = encode_syncsafe(new_frame_size)
                    # Adjust subsequent positions accordingly
                    payload_end += size_diff
                changes.append((f"ID3v2:{frame_id.decode('latin-1')}", repr(orig), repr(trimmed)))

        pos = payload_end

    if not changes:
        return data, []

    # Rebuild: header + (possibly resized) tag body + rest of file
    new_tag_body  = bytes(tag_body)
    new_tag_size  = len(new_tag_body)
    new_header    = (
        b"ID3"
        + bytes([major, data[4], flags])
        + encode_syncsafe(new_tag_size)
    )
    new_data = new_header + new_tag_body + data[header_end + tag_size:]
    return new_data, changes

# =============================================================================
# Main walk
# =============================================================================

mp3_files = []
for root, dirs, files in os.walk(target_dir):
    dirs.sort()
    for fname in sorted(files):
        if fname.lower().endswith(".mp3"):
            mp3_files.append(os.path.join(root, fname))

if not mp3_files:
    print("No MP3 files found.")
    sys.exit(0)

print(f"Found {len(mp3_files)} MP3 file(s).\n")

for filepath in mp3_files:
    try:
        with open(filepath, "rb") as f:
            original = f.read()
    except OSError as e:
        print(f"{YELLOW}Cannot read: {filepath} — {e}{RESET}")
        continue

    # Process both tag types
    after_v2, v2_changes = process_id3v2(original)
    after_v1, v1_changes = trim_id3v1(after_v2)

    all_changes = v2_changes + v1_changes

    if not all_changes:
        continue

    rel = os.path.relpath(filepath, target_dir)
    print(f"{BOLD}{CYAN}{rel}{RESET}")
    for tag_field, orig, trimmed in all_changes:
        print(f"   {YELLOW}{tag_field:<22}{RESET}  {orig}  →  {GREEN}{trimmed}{RESET}")

    if not dry_run:
        try:
            with open(filepath, "wb") as f:
                f.write(after_v1)
            print(f"Saved")
        except OSError as e:
            print(f"   {YELLOW}Could not write: {e}{RESET}")

    print()
    changed_files += 1
    total_changes += len(all_changes)

# ── Summary ───────────────────────────────────────────────────────────────────
print("─" * 50)
if dry_run:
    print(f"DRY RUN complete. Would modify {changed_files} file(s), {total_changes} tag field(s).")
else:
    if changed_files:
        print(f"Done. Modified {changed_files} file(s), {total_changes} tag field(s).")
    else:
        print("All tags are already trimmed. Nothing to do.")
